version: '3.7'

services:
  postgres:
    restart: always
    image: "postgres:13.3-alpine"
    command:
      - postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: bb_db
  app:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - 8000:8000
    command: ['python', 'manage.py', 'runserver_plus', '0.0.0.0:8000']
    environment:
      DATABASE_URI: 'postgresql://testuser:testpassword@postgres:5432/bb_db'

    volumes:
      - './assessment:/srv/app/assessment'
      - './api:/srv/app/api'
      - './web:/srv/app/web'