# Generated by Django 4.0.3 on 2022-03-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bbbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbproperty',
            name='value',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
